# Generated by Django 3.0 on 2019-12-25 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodpoll', '0003_auto_20191208_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodexpression',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
