# Generated by Django 3.0.6 on 2020-06-01 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodpoll', '0004_auto_20191225_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOptionReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_value', models.IntegerField(default=0)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodpoll.PollOption')),
            ],
        ),
        migrations.CreateModel(
            name='PollReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('key', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moodexpression',
            name='poll',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='optionlist',
        ),
        migrations.AddField(
            model_name='poll',
            name='key',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='replies_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MoodExpression',
        ),
        migrations.AddField(
            model_name='pollreply',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodpoll.Poll'),
        ),
        migrations.AddField(
            model_name='polloptionreply',
            name='poll_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodpoll.PollReply'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodpoll.Poll'),
        ),
        migrations.AlterUniqueTogether(
            name='polloptionreply',
            unique_together={('poll_reply', 'poll_option')},
        ),
    ]
