# Generated by Django 3.1 on 2020-09-10 08:57

from django.db import migrations, models
import moodpoll.models


class Migration(migrations.Migration):

    dependencies = [
        ('moodpoll', '0006_auto_20200614_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='key',
            field=models.PositiveIntegerField(default=moodpoll.models.get_rdm_key),
        ),
        migrations.AlterField(
            model_name='pollreply',
            name='key',
            field=models.PositiveIntegerField(default=moodpoll.models.get_rdm_key),
        ),
    ]
