# Generated by Django 3.1.3 on 2021-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodpoll', '0008_auto_20201211_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='mood_value_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='mood_value_min',
            field=models.IntegerField(default=-3),
        ),
    ]
