# Generated by Django 3.1.3 on 2021-01-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodpoll', '0009_auto_20210104_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expose_veto_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='require_name',
            field=models.BooleanField(default=False),
        ),
    ]
