"""
Django settings for the moodpoll django project (not the moodpoll app).

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import deploymentutils as du

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASEDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ensure BASEDIR is as expected
assert os.path.isfile(os.path.join(BASEDIR, "manage.py"))

# get the devmode from environment variable (default: False, except when the server was started with runserver)
# export DJANGO_DEVMODE=True; py3 manage.py some_custom_command
env_devmode = os.getenv("DJANGO_DEVMODE")
if env_devmode is None:
    DEVMODE = "runserver" in sys.argv
else:
    DEVMODE = (env_devmode.lower() == "true")

config = du.get_nearest_config("config.ini", devmode=DEVMODE)

SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

# prevent accidentally using DEBUG == "False" (which evaluates to `True`)
assert DEBUG in (True, False)
assert DEVMODE in (True, False)

# BASEURL = config("BASEURL")

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=config.Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bleach',
    'django_nose',
    'moodpoll',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# "settings" is the name of the django-project
ROOT_URLCONF = 'settings.urls'
WSGI_APPLICATION = 'settings.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASEDIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file1': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': config("DJANGO_LOGFILE").replace("__BASEDIR__", BASEDIR),
            'formatter': 'verbose',
        },
        'file2': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': config("MYAPP_LOGFILE").replace("__BASEDIR__", BASEDIR),
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file1'],
            'level': 'WARNING',
            'propagate': True,
        },
        'myapp': {
            'handlers': ['file2'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# this will be used when rendering the templates
STATIC_URL = '/static/'

# this is the target of manage.py collectstatic
STATIC_ROOT = config("STATIC_ROOT").replace("__BASEDIR__", BASEDIR)


BASEDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# path where db-backups are dumped to
BACKUP_PATH = os.path.join(BASEDIR, "db_backups")

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

# this determines the range of possible values
# in the future these values might be configurable for each poll
# note that this could be overridden by instance specific settings
MOOD_VALUE_MAX = config("MOOD_VALUE_MAX")
MOOD_VALUE_MIN = config("MOOD_VALUE_MIN")  # the lowest value is considered a 'veto'

BLEACH_ALLOWED_TAGS = ['p', 'b', 'i', 'u', 'em', 'strong', 'a',
                       'h1', 'h2', 'h3', 'h4', 'h5', 'ul', 'ol', 'li', 'pre', 'code']
BLEACH_STRIP_COMMENTS = False

