from jinja2 import Environment, PackageLoader, FileSystemLoader
import os

jin_env = Environment(loader=FileSystemLoader('./'))


def render_template(tmpl_path, context):
    path, fname = os.path.split(tmpl_path)

    special_str = "template_"
    assert fname.startswith(special_str) and (fname.count(special_str) == 1) and len(fname) > len(special_str)
    res_fname = fname.replace(special_str, "")

    template = jin_env.get_template(tmpl_path)
    context["warning"] = "This file was autogenerated from the template: {}".format(fname)
    result = template.render(context=context)

    target_path = os.path.join(path, res_fname)

    if 1:
        with open(target_path, "w") as resfile:
            resfile.write(result)

    else:
        print(target_path, "\n"*2, result)
