
# This file was autogenerated from the template: template_site_specific_settings.py


SECRET_KEY = 'fbbgnqZ-ykvWOFCTq4ybeRnmwAKkTxNwXIaBIR9xV3ZgsAzT0bwjYZ2go6dPS2Uif-s'

DEBUG = False

ALLOWED_HOSTS = ['moodpoll.uber.space']

STATIC_ROOT = '~/moodpoll_deployment/collected_static'
