
# This file was autogenerated from the template: template_site_specific_settings.py


SECRET_KEY = mWjLrQdJ9dxzxrnOSyy2JfJXhiSk4QQ3oP0ypT483-pg7cFBplkA_5PKSMsjUKz4yE8

DEBUG = False

ALLOWED_HOSTS = ['moodpoll.uber.space']

STATIC_ROOT = ~/moodpoll_deployment/collected_static
